version: '3'

services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres13:/var/lib/postgresql/data
  redis:
    image: redis:7.0.15-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  web:
    build: .
    volumes:
      - .:/rails
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
  test:
    build: .
    command: bundle exec rspec
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres13:
  redis_data:
