:concurrency: 3
:timeout: 60
:verbose: true
:scheduler:
  schedule:
    mark_cart_as_abandoned:
      class: "MarkCartAsAbandonedJob"
      cron: "0 */1 * * *"
    destroy_unused_carts:
      class: "DestroyUnusedCartsJob"
      cron: "* */7 * * *"
:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
