:concurrency: 3
:timeout: 60
:verbose: true
:schedule:
  mark_cart_as_abandoned:
    name: "MonthlyReportJob"
    cron: "* * * * *"
:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
